### ISSUE TITLE
Installing LINKS with the latest SWIG version 3.0.12

### ISSUE THREAD

**Issue by caonetto** [warrenlr/LINKS#10]
Hi, I am kind of a newbie and I am struggling to install Links,
I have downloaded the tar file and extracted it, I installed SWIG (3.0.12), etc, then got to the TEST INSTALL step and got the following output:
ubuntu@tee9seq:/mnt/cris/links_v1.8.5/lib/bloomfilter/swig$ ./test.pl
de novo bf tests done 
Storing filter. Filter is 125000000bytes.
Loading header...
premade bf tests done
Filter Info: Pop - 20, numHash - 5, kmerSize - 20, size - 1000000000
0 TAGAA found
1 AGAAT found
2 GAATC found
3 AATCA found
4 ATCAC found
5 TCACC found
6 CACCC found
7 ACCCA found
8 CCCAA found
9 CCAAA found
10 CAAAG found
11 AAAGA found
Done!

Is this output ok?

Also I installed LINKS in a different directory, could someone explain me how to do step 4 (CHANGE the path to BloomFilter.pm in LINKS/writeBloom.pl/testBloom.pl)????

Thanks!

Cris.

**Comment by warrenlr** [comment]
Hi Cris,
The test indicate that you have successfully compiled the BloomFilter .pm module
You could try some test LINKS scaffolding examples to verify the rest of your install.
Cheers,
Rene
