### ISSUE TITLE
Output relative to preexisting scaffold names?

### ISSUE THREAD

**Issue by yannickwurm** [warrenlr/LINKS#2]
Hello,
Links seems to use its own internal scaffold names. 
For the output to be usable I'd really want a table reusing the names in my old assembly. (and ideally this table would also indicate which or how many reads support each link; I understand if algorithmically the latter is unfeasible). The AGP format (or the format used by 454 back in the day) are relatively standard...
Kind regards,
Yannick

**Comment by yannickwurm** [comment]
(if doing this is slow, it would not be a problem for it to be performed in an additional step)

**Comment by warrenlr** [comment]
yes it is feasible and in anticipation, the code is already set up to track this information.. I just never got around to finalizing it. 
In the .scaffolds, each scaffold is listed with the information from the original (but re-numbered) contigs. It was developed in such fashion to avoid long inconsistent names and streamline the process (this was done many years before AGP or any "standards", so never adopted. This file is read by LINKS to produce the final, .scaffolds.fa output

eg.
scaffold13,248015,f21465z18090k8a0m-245_f37Z158847k7a0m-265_r779z71078 

scaffold 13 is comprised of contig 21465(forward 18090bp), 37(forward 158847bp), and 779 (reverse-strand 71078bp). The size of each is captured after "z". The number of kmer pairs is indicated after "k" and the #links ratio "a" of 0 in each case indicates that no alternate pairing exists with other contigs. Two overlaps (-245bp and -265) are calculated based on kmer pair distance info.

Easiest fix for me until I work on developing a new format, is to output a .tsv, with the contig number and your original name:

eg. 

1     21 551 1411
2     22 968 10458
...

cheers,
Rene

**Comment by warrenlr** [comment]
I've released 1.6.1 on github.
See release notes

**Comment by warrenlr** [comment]
I have added a field that reports the orientation of the contig.  Use the latest version instead.  I don't expect to make any additional changes to the format.

**Comment by yannickwurm** [comment]
ok thanks
