### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by druvus** [warrenlr/LINKS#3]
I started to look into updating the bioconda recipe for LINKS. Looking through the code I realized that LINKS is using GPL2 while the included bcgsc version of bloomfilter still uses a custom bcca license. I would be happy if you could look into this as those two licenses are not compatible.

**Comment by warrenlr** [comment]
thanks for bringing this to my attention, we will look into it.

**Comment by warrenlr** [comment]
LINKS v1.8.4 is released under GPL-3 and the library dependency to lib/rolling-hash and lib/bloomfilter are now also licensed under GPL-3. For alternative licensing terms, please contact Patrick Rebstein (prebstein at bccancer.bc.ca)

**Comment by druvus** [comment]
Thanks for the quick fix.
