### ISSUE TITLE
BloomFilter_wrap.cxx:762:20: fatal error: EXTERN.h: No such file or directory

### ISSUE THREAD

**Issue by csuliweilong** [warrenlr/LINKS#4]
I installed pcre and swig properly to meet the prerequisites of links.

However, when it comes to step b) of  `TO BUILD a Perl5 module (run in swig/)`:, I got the problem below:

```

BloomFilter_wrap.cxx:762:20: fatal error: EXTERN.h: No such file or directory

compilation terminated.
```

How to fix this?

Thank you!

**Comment by warrenlr** [comment]
Did you ensure that the path to the perl CORE is valid on your system?

e.g.
a) /home/<user>/<path to swig>/preinst-swig -Wall -c++ -perl5 BloomFilter.i
b) g++ -c BloomFilter_wrap.cxx -I/usr/lib64/perl5/CORE -fPIC -Dbool=char -O3
c) g++ -Wall -shared BloomFilter_wrap.o -o BloomFilter.so -O3
