### ISSUE TITLE
Issue Building BloomFilter Perl5 Module

### ISSUE THREAD

**Issue by wwcgeneticslab** [warrenlr/LINKS#5]
I am running LINKS on a virtual Ubuntu machine. When I get to step b and c building the module, the -03 option throws an error: "unrecognized command line option '-03' ." I am able to execute both b and c without "-03". Should this be a problem?

My main issue is that after setting up the perl5 module, I tried to run the test file and get this error:
Can't load './BloomFilter.so' for module BloomFilter: ./BloomFilter.so: undefined symbol: PL_stack_sp at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 187.
 at BloomFilter.pm line 11.
Compilation failed in require at ./test.pl line 3.
BEGIN failed--compilation aborted at ./test.pl line 3.
I then ran the test as root and got a Segmentation fault (core dumped) error. 
Do you know what might be going on?
I'm really new to command line, so forgive me if I'm missing something obvious. Let me know if you need more info as well.
Thanks!

**Comment by warrenlr** [comment]
Hello, 
-O3 is the "Optimize" flag. It should be the letter O, not a zero.
Cheers
