### ISSUE TITLE
AGP file Generation

### ISSUE THREAD

**Issue by bistace** [warrenlr/LINKS#8]
Hi,
I used LINKS 1.8.5 to scaffold a 100Mb genome and am very happy with the results. However, I would like to generate an AGP file, is there a way to do so with the available output files ?

**Comment by warrenlr** [comment]
Thank you for your comment. 
Yes, this [generating AGP] is something that I meant to do .. though I don't have a solution at hand.
Looking at https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/
it looks pretty straightforward and I believe, looking at it quickly, that LINKS outputs all the necessary info needed for this conversion.
In particular the .scaffolds file *and* less cryptic and perhaps more akin to the AGP2 format is the .assembly_correspondence.tsv -- I'll have to get back to you on this though.
@sjackman may have some insights as he co-wrote AGP2 and is familiar with the LINKS output.

**Comment by warrenlr** [comment]
I wrote a basic script to convert LINKS _.scaffolds_ to AGPv2.  
It is not fully tested. I hope that my interpretation of the AGPv2 format is correct, but can't provide guarantees.
I encourage you to contribute to it, if you'd like.
https://github.com/warrenlr/LINKS/blob/master/scaffoldsToAGP2.pl

**Comment by warrenlr** [comment]
Perhaps a better solution for generating an AGP file, is to convert the scaffolds.fa file LINKS produces to AGP using abyss-fatoagp. This way, gaps in drafts prior to LINKS scaffolding will be reported in the file.

**Comment by sjackman** [comment]
`abyss-fatoagp` is included with ABySS or you can download it separate from GitHub: https://github.com/bcgsc/abyss/blob/master/bin/abyss-fatoagp

**Comment by bistace** [comment]
Hi, a big thank you to you all for your help, I really appreciate it!

**Comment by dcopetti** [comment]
Hi,
I also would like to produce an agp file from the LINKS step. I tried the scaffoldsToAGP2.pl up here but I got an incomplete agp:
.scaffold file:
```[...]
scaffold5,3706426,f15765z29267k6a0m100_f3613Z2327823k8a0m100_f15766z304842k5a0m100_f3614z1044494
[...]
scaffold7,3130224,f2421Z2257146k9a0m100_f8145z813619k5a0m100_f37087z59459
scaffold8,2952919,r6145z699742k6a0m100_f6144Z2253177```

.agp:
```scaffold5       1       1       1       N       NA      NA      NA      scaffold        NA      yes     NA      paired-ends
scaffold5       1       1       2       N       NA      NA      NA      scaffold        NA      yes     NA      paired-ends
scaffold5       1       1       3       N       NA      NA      NA      scaffold        NA      yes     NA      paired-ends
scaffold5       1       1044495 4       N       3614    NA      NA      scaffold        NA      yes     +       paired-ends
[...]
scaffold7       1       1       1       N       NA      NA      NA      scaffold        NA      yes     NA      paired-ends
scaffold7       1       1       2       N       NA      NA      NA      scaffold        NA      yes     NA      paired-ends
scaffold7       1       59460   3       N       37087   NA      NA      scaffold        NA      yes     +       paired-ends
scaffold8       1       1       1       N       NA      NA      NA      scaffold        NA      yes     NA      paired-ends
scaffold8       1       2253178 2       N       6144    NA      NA      scaffold        NA      yes     +       paired-ends```

I am scaffolding with 10x data scaffolds obtained with short reads, and I would like to see the effect of this last scaffolding by aligning to an optical map. If I use the  abyss-fatoagp script, I get the right gap posistions, but they include also the gaps I already had.
Is there a convenient way to turn LINKS output to an .agp format that takes the input sequences as "whole units"?
Thanks!

**Comment by warrenlr** [comment]
hmm, I'm afraid I don't understand the example you showed. Could you please clarify?
Are you saying that there are records in the .scaffolds that are not listed in the .agp (is that scaffold6 in your example)?

**Comment by warrenlr** [comment]
I pushed edits to the scaffoldsToAGP2.pl in the master branch
Its output is now similar to abyssfatoagp, but only reports gaps from links/arcs (as listed in the .scaffolds)
 -- let me know how it goes.

**Comment by dcopetti** [comment]
Thanks!
I run the new script and indeed the format is different now. Example for scf5:
`scaffold5,3706426,f15765z29267k6a0m100_f3613Z2327823k8a0m100_f15766z304842k5a0m100_f3614z1044494`
gives:
```
scaffold5       1       0       1       W       oriscaffold_NA  1       0       NA
scaffold5       1       0       2       N       NA      scaffold        yes     paired-ends
scaffold5       1       0       3       W       oriscaffold_NA  1       0       NA
scaffold5       1       0       4       N       NA      scaffold        yes     paired-ends
scaffold5       1       0       5       W       oriscaffold_NA  1       0       NA
scaffold5       1       0       6       N       NA      scaffold        yes     paired-ends
scaffold5       1       1044494 7       W       oriscaffold_3614        1       1044494 +
```
what I meant above was something where I can see the start/stop cords of each sequence and gap in the scaffold, and their individual size. Something like this:
```
chr1A   0       512575  scaffold_corrected_1229 1       +
chr1A   512575  512675  gap     2       +
chr1A   512675  1227143 scaffold_corrected_794  3       -
chr1A   1227143 1227243 gap     4       +
chr1A   1227243 3115654 scaffold_corrected_1080 5       +
chr1A   3115654 3115754 gap     6       +
chr1A   3115754 4701957 scaffold_corrected_665  7       +
chr1A   4701957 4702057 gap     8       +
chr1A   4702057 7855993 scaffold_corrected_1338 9       +
chr1A   7855993 7856093 gap     10      +
chr1A   7856093 11520347        scaffold_corrected_498  11      +
```
like this example: https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/

I can see some details from the .scaffolds file, but those are not so immediate to read.
Just if you have anything handy, or that would be easy to write down.
Thanks!

**Comment by warrenlr** [comment]
oh, sorry, I didn't factor in the slightly different format of the arcs .scaffolds file

I pushed the bug fixed version
`
rwarren03:LINKS rwarren$ ./scaffoldsToAGP2.pl test.scaff 
scaffold5	1	29267	1	W	oriscaffold_15765	1	29267	+
scaffold5	29268	29367	2	N	100	scaffold	yes	paired-ends
scaffold5	29368	2357190	3	W	oriscaffold_3613	1	2327823	+
scaffold5	2357191	2357290	4	N	100	scaffold	yes	paired-ends
scaffold5	2357291	2662132	5	W	oriscaffold_15766	1	304842	+
scaffold5	2662133	2662232	6	N	100	scaffold	yes	paired-ends
scaffold5	2662233	3706726	7	W	oriscaffold_3614	1	1044494	+
`

**Comment by dcopetti** [comment]
looks perfect!
Thank you very much!!

**Comment by sjackman** [comment]
Note the NCBI GenBank accepts assemblies with gaps now.
See *Gapped Format for Genome Submissions* https://www.ncbi.nlm.nih.gov/genbank/wgs_gapped/

**Comment by shameem356** [comment]
Hello @sjackman @warrenlr ,

First of all I want to say thank for Tigmint+LINKS pipeline. By using Tigmint+LINKS pilpein made an amazing de-novo plant genome assembly.Now we are planing to submit the genome to NCBI.But we are having a problem with AGP file.We tried to create AGP file using abyss-fatoagp program and it could not make correct AGP file .The reason because we have used pilon software with gap insert mode (10bp ) to polish the base assembly (pacbio ) before ARCS pipeline. Then the  base assembly ran with TIGMINT and ARCS with four set of 10X data. 

The final output is having 10bp 'Ns' from ARCS as well as pilon. This messed up the abyss-fatoagp out put.Please could you give an advise how to solve this issue ? I can explain you in detail the process we have done.
1. created base assembly with  pacbio reads.
2. ran Quiver and pilon for correction and polishing of genome . Pilon ran with gap insert mode. it inserted 10bp gaps.
3. Generated four sets of 10x data : a. Leaf_plg, b. leaf , c. shoot d . shoot_plud
4. Run tigmint with four sets of 10X data recursively ( leaf-plug -> leaf -> shoot -> shoot_plug)
5. Run  ARCS with four sets of 10X data recursively  ( leaf-plug -> leaf -> shoot -> shoot_plug).

Now I want to create AGP file for assembly ????

**Comment by dcopetti** [comment]
hello again,
I wonder LINKS or Abyss have (or if you know of) a tool that does the opposite of what I asked above.
This time I have a set of scaffolds and an agp file that anchors them in pseudomolecules. Is there a way to build them from an agp?
Thanks,
Dario

**Comment by warrenlr** [comment]
Hi Dario, LINKS doesn't.. not sure about other tools though.
Cheers,
Rene

**Comment by lcoombe** [comment]
Hi Dario,
ABySS doesn't have that either, and I can't think of any of our other tools that would do that conversion, unfortunately. I did a quick search, and there appears to be some scripts out there for this: https://www.biostars.org/p/69964/ (I haven't used them before, though, so can't comment on their quality).

**Comment by dcopetti** [comment]
thank you for pointing that out, @lcoombe ! that page did not come up in my search.
In the meanwhile I found a workaround, but that tool may come useful later on.
Cheers
